name: Déploiement Firebase Hosting + Functions

on:
  push:
    branches:
      - main  # Branche où tu veux déclencher le déploiement

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Installer les dépendances React/Vite
        run: npm install

      - name: Construire le site React/Vite
        run: npm run build

      - name: Installer les dépendances des Firebase Functions
        run: npm install
        working-directory: functions

      - name: Installer Firebase CLI
        run: npm install -g firebase-tools

      - name: Déployer Hosting + Functions sur Firebase
        run: firebase deploy --project=buyticle-bce3f --only hosting,functions --token "${{ secrets.FIREBASE_TOKEN }}"
